<!-- Filename: /module/Blog/view/blog/write/add.phtml -->
<div class="conteneur">
 <h1>add a blog: </h1>
<a href="<?php echo $this->url('blog');?>">
 <span class="btn btn-lg btn-primary" >Return to the blog list </span>
</a>
<br><br>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url());
 $form->prepare();

 echo $this->form()->openTag($form);

 echo $this->formCollection($form);

 echo $this->form()->closeTag();
?>
</div>