<!-- Filename: /module/Blog/view/blog/list/index.phtml -->
<div class="conteneur">
    <div class="haut">
        <a class="floatant" href="<?php echo $this->url('blog/add'); ?>">
            <span class="btn btn-lg btn-success">Add new blog </span>
        </a>
        <h1 class="titre">Blog</h1>


    </div>

    <?php
    $i = 0;
    foreach ($this->posts as $post): ?>
        <article class="inline">

            <h2 id="post<?= $post->getId() ?>"><?= $post->getTitle() ?></h2>
            <p class="test">
                <?= $post->getText() ?>
            </p>

        </article>
    <?php endforeach ?>
</div>
