<!-- Filename: /module/Blog/view/blog/list/index.phtml -->
 <h1>Blog</h1>

    <a href="<?php echo $this->url('blog/add');?>">
        <span class="btn btn-lg btn-success" >Add new blog </span>
    </a>

 <?php foreach ($this->posts as $post): ?>
 <article>

     <h1 id="post<?= $post->getId() ?>"><?= $post->getTitle() ?></h1>
     <p>
         <?= $post->getText() ?>
     </p>
 </article>
 <?php endforeach ?>
